version: 0.2

phases:
  install:
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - cd ./frontend
      - yarn install
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - echo copy appspec to dist
      - cp -r -u ./aws/codedeploy/ ./dist/
artifacts:
  files:
    - '**/*'
  base-directory: frontend/dist