version: 0.2

phases:
  install:
    runtime-versions:
      java: latest
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew bootJar
  post_build:
    commands:
      - echo copy appspec to distributed directory
      - cp -r -T ./aws/codedeploy ./build/libs
artifacts:
  files:
    - '**/*'
  base-directory: build/libs